apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: flask-deployment
spec:
  selector:
    matchLabels:
      app: flask-crud-app
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: flask-crud-app
    spec:
      containers:
      - name: flask-crud-app
        image: kakashi96/flask-crud-app
        ports:
        - containerPort: 80